### ISSUE TITLE
Error found by the locate mod errors function

### ISSUE THREAD

**Issue by nizhuan-jjr** [Lasty120/Leaders-Plus#3]
Greatest General can place improvement Citadel which has no stats, preventing unit automation!
![Screenshot_20230524_094110_com unciv app](https://github.com/Lasty120/Leaders-Plus/assets/3255986/3b9eb822-a787-4d47-9eb3-270e887472cd)

**Comment by Lasty120** [comment]
This is not a bug, everything works fine. Since the characteristics of the citadel were not changed in the mod, and the vanilla version is used, Unciv complains.
